# This project usese Tilt to manage the development environment.
# The project_name is used to namespace the docker-compose services.
docker_compose("./docker-compose.yml", project_name="mlops-hack")

# Frontend resources.
# The local_resource function runs a command on the local machine.
local_resource("vector-visualizer",
  allow_parallel=True,
  serve_cmd="cd ../visualizevectors; npm run dev",
  labels="frontend",
  links=[
    link("http://localhost:5173", "Frontend"),
  ],
)

# Backend resources.
local_resource("slack-monitor",
  allow_parallel=True,
  serve_cmd="cd ../slack-monitor; go run .",
  labels="backend",
)
local_resource("python-service",
  allow_parallel=True,
  serve_cmd="cd ../llm-stack-hack-python-service; make run",
  labels="backend",
)
# dc_resource("gateway", labels="backend")

# Observability and Telemetry
# dc_resource("jaeger", labels="telemetry")
# dc_resource("otel-collector", labels="telemetry")
# dc_resource("prometheus", labels="telemetry")

# Storage
#dc_resource("database", labels="storage")
dc_resource("redis", labels="storage")

# # Browser Tests
# local_resource("browser-tests",
#   allow_parallel=True,
#   serve_cmd="cd ../load-generation; make run-browser-load-generation-via-chrome-ws",
#   labels="browser-tests",
#   auto_init=False,
# )
